import {StyleSheet} from 'react-native';
import {scale, verticalScale} from 'react-native-size-matters';

export default styles = StyleSheet.create({
  headerIcon: {width: 24, height: 24, marginRight: 10},
  error: {
    color: '#ED4337',
    alignSelf: 'flex-end',
    fontSize: scale(12),
    marginBottom: 10,
  },
  image: {
    height: 20,
    width: 20,
    marginRight: 20,
  },
  listHeading: {
    fontSize: 16,
    fontWeight: '700',
    color: '#000',
  },
  listSubheading: {
    fontSize: 14,
    fontWeight: '500',
    color: '#000',
  },
  inputPassView: {
    width: '80%',
    height: 60,
    borderRadius: 30,
    marginBottom: 10,
    paddingLeft: 10,
    borderWidth: 1,
    paddingRight: 10,
    borderColor: '#1A81C4',
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'space-between',
  },
  profileImage: {
    height: verticalScale(),
  },
  headerIcon: {width: 24, height: 24, marginRight: 10},
  spaceLine: {
    height: 1,
    width: '100%',
    backgroundColor: '#ccc',
    marginVertical: scale(5),
  },
  image: {
    height: 20,
    width: 20,
    marginRight: 10,
  },
  profileImageView: {
    width: 110,
    height: 110,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    margin: 5,
    // elevation: 2,
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 8,
  },

  inputHeading: {
    color: '#000',
    fontWeight: '500',
    fontSize: scale(16),
    paddingBottom: 5,
  },
  inputPassView: {
    width: '100%',
    height: 50,
    borderRadius: 10,
    marginBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: '#F1F1F1',
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'space-between',
  },
});
export const colorGlobal = {
  black: '#000',
  white: '#fff',
  yellow: 'yellow',
  blue: 'blue',
  appointmentHeader: '#F5F5F5',
  // themeColor: '#1A81C4',
  medicine: '#883d3d',
  themeColor: '#009281',
  seaGreen: '#20B2AA',
  lightSeaGreen: '#DBF7F2',
  lightWhite: '#F1F1F1',
  orange: 'red',
  black: '#000',
  white: '#fff',
  yellow: 'yellow',
  blue: 'blue',
  gray: 'gray',
  lightgray: '#ccc',
  // themeColor: '#1A81C4',
  chatSenderColr: '#d1e7ff',
  error: '#F33E3E',
};
